## ~/Applications
# - PortfolioPerformance
# - Qt
# - VSCode-linux-x64
# - FastPhotoTagger
- name: Create base directories
  ansible.builtin.file: path={{ item }} state=directory mode=0700
  with_items:
    - ~/Applications
    - ~/.bin
    - ~/.local/share/applications

- name: Copy ~/.gitconfig
  ansible.builtin.template: src=gitconfig dest=~/.gitconfig mode=0600

- name: Copy FastPhotoTagger desktop file
  ansible.builtin.copy: src=desktop-files/fastphototagger.desktop dest=~/.local/share/applications mode=0755

- name: Copy PortfolioPerformance desktop file
  ansible.builtin.copy: src=desktop-files/portfolio-performance.desktop dest=~/.local/share/applications mode=0755

- name: Enable syncthing service
  ansible.builtin.systemd: name=syncthing scope=user enabled=yes state=started

- name: Copy VSCode desktop file
  ansible.builtin.copy: src=desktop-files/visual-studio-code.desktop dest=~/.local/share/applications mode=0755

