- name: create empty .bash_sessions_disable
  copy:
    content: ""
    dest: "~/.bash_sessions_disable"
    mode: 0400

- name: copy bash configuration files
  copy:
    src: "{{ item }}"
    dest: "~/.{{ item }}"
    mode: 0400
  loop:
    - bash_profile
    - bashrc
    - banner

- name: create ~/bin
  file:
    path: "~/bin"
    state: directory
    mode: 0700
