- name: base > Install base tools
  community.general.pacman: name={{ item }}
  with_items:
    - acpi
    - base-devel
    - curl
    - exfat-utils
    - fzf
    - git
    - lm_sensors
    - lshw
    - nmap
    - man-db,man-pages
    - openssh
    - pacman-contrib
    - python,python-psutil
    - rsync
    - screen
    - smbclient
    - tree
    - unrar,unzip,xz
    - zsh,zsh-autosuggestions

- name: base > Enable locale
  ansible.builtin.lineinfile:
    dest: /etc/locale.gen
    regexp: '^#({{ item }})$'
    line: '\1'
    backrefs: yes
  with_items:
    - 'en_US.UTF-8 UTF-8'
    - 'fr_FR.UTF-8 UTF-8'
  notify: locale-gen

- name: base > Set system locale
  ansible.builtin.lineinfile: dest=/etc/locale.conf line={{ item }} create=yes
  with_items:
    - 'LANG=fr_FR.UTF-8'
    - 'LC_MESSAGES=en_US.UTF-8'

- name: base > Set console keymap
  ansible.builtin.lineinfile: dest=/etc/vconsole.conf line="KEYMAP=fr" create=yes

- name: x-base > Ensure /etc/X11/xorg.conf.d exists
  ansible.builtin.file: path=/etc/X11/xorg.conf.d state=directory

- name: base > Set X keyboard
  ansible.builtin.copy: src=00-keyboard.conf dest=/etc/X11/xorg.conf.d/00-keyboard.conf

- import_tasks: base-aur.yml
