- name: devapps > Install dev apps & tools packages
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - cmake
      - gdb
      - pycharm-community-edition

- name: devapps > Install dev apps & tools from AUR
  aur: name={{ packages | join(',') }} use=makepkg state=present
  become: yes
  become_user: aur_builder
  vars:
    packages:
      - visual-studio-code-bin
