
- name: fonts > Install fonts
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-serif-jp-fonts
      - noto-fonts,noto-fonts-cjk,noto-fonts-emoji
      - ttf-dejavu,ttf-liberation

- name: fonts > Enable fonts presets
  ansible.builtin.file: state=link src="/usr/share/fontconfig/conf.avail/{{ item }}" path="/etc/fonts/conf.d/{{ item }}"
  with_items:
    - 10-sub-pixel-rgb.conf
    - 11-lcdfilter-default.conf
    - 70-no-bitmaps.conf
