- name: network > Install network tools & services
  community.general.pacman: name={{ item }}
  with_items:
    - avahi,nss-mdns  # replace with systemd-resolved built-in mDNS

- name: network > Enable mDNS hostname resolution
  ansible.builtin.lineinfile:
    path: /etc/nsswitch.conf
    regexp: '^hosts: files mymachines(.*)'
    line: 'hosts: files mdns4_minimal [NOTFOUND=return] mymachines\1'
    backrefs: yes

- name: network > Enable network services
  ansible.builtin.systemd: name={{ item }} enabled=yes state=started
  with_items:
    - avahi-daemon
    - systemd-networkd
    - systemd-resolved
