- name: userapps > Install my favorites apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - anki
      - chromium
      - exiv2
      - firefox
      - geary
      - gnucash
      - gthumb
      - hunspell,hunspell-fr
      - imagemagick
      - inkscape
      - libreoffice-still,libreoffice-still-fr,ttf-dejavu
      - keepassxc
      - ncmpcpp
      - perl-image-exiftool
      - pycharm-community-edition
      - quodlibet
      - rawtherapee
      - scite
      - vlc

- name: userapps > Install my favorites apps from AUR
  aur: name={{ packages | join(',') }} use=makepkg state=present
  become: yes
  become_user: aur_builder
  vars:
    packages:
      - visual-studio-code-bin
      - portfolio-performance-bin
