- name: userapps > Install my base apps
  community.general.pacman: name={{ packages | join(',') }}
  vars:
    packages:
      - anki
      - chromium
      - firefox
      - geary
      - gnucash
      - hunspell,hunspell-fr
      - imagemagick
      - inkscape
      - libreoffice-still,libreoffice-still-fr,ttf-dejavu
      - keepassxc
      - mpc,ncmpcpp
      - pdfarranger
      - quodlibet
      - syncthing
      - vlc

- name: userapps > Install PortfolioPerformance dependencies
  community.general.pacman: name=jre11-openjdk
