#!/bin/sh

#. Start companion softwares
sxhkd -m 1 &
picom &
feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg
$HOME/.config/polybar/launch.sh

#. Monitors
bspc monitor -d 1 2 3 4 5 6 7 8
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

#. Windowing & Pointer
bspc config border_width    2
bspc config window_gap      10
bspc config top_padding     20

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config click_to_focus          any
bspc config focus_follows_pointer   false

#. Color scheme

#. Specific rules for some applications
