- name: bash's configuration files
  block:
    - name: create empty .bash_sessions_disable
      copy:
        content: ""
        dest: "~/.bash_sessions_disable"
        mode: 0400
    - name: copy bash's configuration files
      copy:
        src: "{{ item }}"
        dest: "~/.{{ item }}"
        mode: 0400
      loop:
        - bash_profile
        - bashrc
        - banner

- name: git global configuration
  command: "{{ item }}"
  loop:
    - "git config --global user.name vinymeuh"
    - "git config --global user.email vinymeuh@gmail.com"
    - "git config --global credential.helper osxkeychain"

- name: npm configuration
  block:
    - name: define npm prefix directory path
      set_fact:
        npm_prefix: "{{ '~/.npm-global' | expanduser }}"
    - name: create directory {{ npm_prefix }}
      file:
        path: "{{ npm_prefix }}"
        state: directory
    - name: retrieve current npm prefix configuration
      shell: npm config get prefix
      register: current_npm_prefix
      changed_when: false
    - name: set npm prefix to {{ npm_prefix }}
      command: npm config set prefix '{{ npm_prefix }}'
      when: current_npm_prefix.stdout != npm_prefix
    - name: install global npm packages
      npm:
        name: "{{ item }}"
        global: yes
      loop:
        - "elm-format"
        - "elm-test"