- name: base > Create base directories
  file: path="{{ item }}" state=directory mode=0700
  with_items:
    - "~/.bin"
    - "~/Applications"

- name: base > Check fish shell is available
  command: which fish
  register: which_fish
  changed_when: false
  ignore_errors: true

- name: base > Fail if fish shell is not available
  fail: msg="fish shell in not available, install it and retry"
  when: which_fish.rc != 0

- name: base > Fail if user default shell is not fish
  fail: msg="user default shell is not fish, fix it and retry"
  when: ansible_facts.user_shell is not match("/.*/fish$")
