- name: base > Create base directories
  file: path="{{ item }}" state=directory mode=0700
  with_items:
    - "~/.bin"
    - "~/Applications"

- name: base > Check fish shell is available
  command: which fish
  changed_when: False

- name: base > Fail if user default shell is not fish
  fail: msg="user default shell is not fish, fix it and retry"
  when: 
    - (ansible_os_family != "Darwin" and ansible_facts.user_shell is not match("/.*/fish$"))
