- name: base > Create some directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "~/.bin"
    - "~/.opt"

- name: nyx > Check fish shell is available
  shell: cmd="which fish" 
  register: which_fish
  changed_when: false
  ignore_errors: true
- name: nyx > Fail if fish shell is not available
  fail: msg="fish shell in not available, install it and retry"
  when: which_fish.rc != 0

- name: nyx > Fail if user default shell is not fish
  fail: msg="user default shell is not fish, fix it and retry"
  when: ansible_facts.user_shell is not match("/.*/fish$")

- name: nyx > Check rcm is available
  shell: cmd="which rcm" 
  register: which_rcm
  changed_when: false
  ignore_errors: true
- name: nyx > Fail if rcm is not available
  fail: msg="rcm in not available, install it and retry"
  when: which_rcm.rc != 0

- name: nyx > Create symbolic link ~/.rcrc
  file: src="~/Nyx/dotfiles/rcrc" dest="~/.rcrc" state=link

- name: nyx > rcup -f -v
  shell: cmd="rcup -f -v"
