- name: firewall > Install ufw package
  xbps: name=ufw

- name: firewall > Enable ufw IPV6 support
  lineinfile: path=/etc/default/ufw regexp='^IPV6=' line='IPV6=yes'

- name: firewall > Set ufw default policies
  ufw: direction={{ item.direction }} default={{ item.default }}
  with_items:
    - { direction: "incoming", default: "deny" }
    - { direction: "outgoing", default: "allow" }
    - { direction: "routed", default: "deny" }

- name: firewall > Allow incoming SSH from RFC1918 class C
  ufw: port=ssh rule=allow src=192.168.0.0/16

- name: firewall > Enable ufw at boot
  runit: name=ufw enabled=yes state=started
