- name: gnome > Install D-Bus
  xbps: name=dbus

- name: gnome > Enable & Start D-Bus service
  runit: name=dbus enabled=yes state=started

- name: gnome > Install Gnome
  xbps: name=gnome,gnome-screensaver,dconf-editor

# Don't use GDM as is does not care of my french keyboard
# - name: gnome > Enable GDM
#   runit: name=gdm state=started

- name: gnome > Install LightDM
  xbps: name=lightdm,lightdm-gtk3-greeter

- name: gnome > Enable LightDM
  runit: name=lightdm state=started
