- name: main > Refresh XBPS repositories indexes
  xbps: name=void-repo-nonfree update_cache=yes

# Base system
- import_tasks: audio.yml
- import_tasks: firewall.yml
- import_tasks: apps-base.yml

# Graphical Desktop
- import_tasks: x-base.yml
- import_tasks: x-bspwm.yml

# Applications (cli & graphical)
- import_tasks: apps.yml
