- name: copy dropbackup under ~/bin
  copy:
    src: "dropbackup"
    dest: "~/bin"
    mode: 0700

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/Library/Logs/dropbackup"

- name: create launchd pfile
  template:
    src: "nyx.dropbackup.plist.j2"
    dest: "~/Library/LaunchAgents/nyx.dropbackup.plist"

- name: start dropbackup launchd service
  command: "{{ item }}"
  loop:
    - launchctl unload ~/Library/LaunchAgents/nyx.dropbackup.plist
    - launchctl load   ~/Library/LaunchAgents/nyx.dropbackup.plist
    - launchctl start nyx.dropbackup