# warning: borgbackup 1.1.9 broken in macports due to msgpack version
# see is_supported__msgpack() in site-packages/borg/helpers.py for a quick and ugly fix
# - name: install borgbackup
#   macports:
#     name: "borgbackup"
#   become: yes

- name: copy disaster under ~/bin
  copy:
    src: "disaster"
    dest: "~/bin"
    mode: 0500

- import_tasks: dropbackup.yml
- import_tasks: keecopy.yml
