- name: apps > Install applications
  macports: name={{ item.name | default(item) }} variant={{ item.variant | default(omit) }}
  with_items:
    - asciidoctor
    - bash
    - bash-completion
    - cmake
    - exiftool
    - exiv2
    - fish
    - git
    - gnutar
    - graphviz
    - ImageMagick
    - most
    - ncmpcpp
    - { name: "nginx", variants: "-flv -mp4 +status" }
    - { name: "nmap", variants: "-subversion" }
    - osxfuse
    - pkgconfig
    - rcm
    - rclone
    - rsync
    - ssh-copy-id
    - tree
    - unrar
    - wget
    - xz    
