# bashrc
#  by default, only used by interactive non-login shell

#. bootstrap nyx
export NYX_HOME="$HOME/Library/nyx"
export NYX_LOCAL="$HOME/Library/nyx-local"
export NYX_LOGS="$HOME/Library/Logs/nyx"

#. functions to help us manage paths (shamelessly borrowed from Linux From Scratch)
#. second argument is the name of the path variable to be modified (default: PATH)
pathremove () {
    local IFS=':'
    local NEWPATH
    local DIR
    local PATHVARIABLE=${2:-PATH}
    for DIR in ${!PATHVARIABLE} ; do
        if [ "$DIR" != "$1" ] ; then
            NEWPATH=${NEWPATH:+$NEWPATH:}$DIR
        fi
    done
    export $PATHVARIABLE="$NEWPATH"
}

pathprepend () {
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="$1${!PATHVARIABLE:+:${!PATHVARIABLE}}"
}

pathappend () {
    pathremove $1 $2
    local PATHVARIABLE=${2:-PATH}
    export $PATHVARIABLE="${!PATHVARIABLE:+${!PATHVARIABLE}:}$1"
}
export -f pathremove pathprepend pathappend

#. set locale
export LANG=fr_FR.UTF-8
export LC_MESSAGES=en_US.UTF-8

#. for macos, see man path-helper  
if [ -x /usr/libexec/path_helper ]; then eval $(/usr/libexec/path_helper -s); fi

#. Nix & Nixpkgs
if [ -L "$HOME/.nix-profile" ]; then

    # single user installation
    source $HOME/.nix-profile/etc/profile.d/nix.sh
    [[ -z "$NIX_USER_PROFILE_DIR" ]] && export NIX_USER_PROFILE_DIR="/nix/var/nix/profiles/per-user/$USER"

    pathprepend "$HOME/.nix-profile/bin"
    pathprepend "$HOME/.nix-profile/share/man" MANPATH

    if [ -f "$HOME/.nix-profile/etc/profile.d/bash_completion.sh" ]; then
        source "$HOME/.nix-profile/etc/profile.d/bash_completion.sh";
    fi

    # check with pkg-config --list-all
    export PKG_CONFIG_PATH="$HOME/.nix-profile/lib/pkgconfig"

    export CMAKE_INCLUDE_PATH="$HOME/.nix-profile/include"
    export CMAKE_LIBRARY_PATH="$HOME/.nix-profile/lib"
fi

#. Go
if [ -x /usr/local/go/bin/go ]; then
    export PATH=$HOME/go/bin:$HOME/Local/Library/Go/Current/bin:$PATH
fi

#. XDG user dirs
pathprepend "$HOME/.local/bin"

#. Nyx himself
pathprepend "$NYX_HOME/bin"
pathprepend "$NYX_LOCAL/bin"

#. short-circuit for non-interactive shell
case "$-" in
    *i*);;
    *) return;;
esac

#. add ":" to re-enable access to the standard system man pages
export MANPATH=$MANPATH:

#. bash shopt buitlin (https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html)
shopt -s cdspell checkhash checkwinsize
shopt -s histappend histreedit histverify lithist
if [[ $BASH_VERSION =~ ^4.* ]]; then
    shopt -s autocd direxpand dirspell
fi

export HISTCONTROL=ignoreboth:erasedups

#. readline setup
set -o emacs

#. add environment variables for interactive shell
export PAGER=less
which -s most
if [ $? -eq 0 ]; then export MANPAGER=most; fi

export GIT_EDITOR=vi

#. banner
if [ -f "$NYX_HOME"/etc/banner.txt ]; then
    if [[ $0 == "-bash" ]]; then
        (echo "cat <<EOF" ; cat $NYX_HOME/etc/banner.txt ; echo EOF ) | $SHELL 2>/dev/null
    else
        (echo "cat <<EOF" ; cat $NYX_HOME/etc/banner.txt ; echo EOF ) | $0 2>/dev/null
    fi
fi

#. set bash prompt
prompt_command () {
    if [ $? -eq 0 ]; then local rc="ok"; else local rc="ko"; fi    
    local green='\e[0;36m'
    local red='\e[0;31m'
    local nc='\e[0m'
    case $rc in
        ok) export PS1="${green}\u@\h ~> ${nc}";;
        ko) export PS1="${red}\u@\h ~> ${nc}";;
    esac
}
export PROMPT_COMMAND=prompt_command

#. cleanup
unset pathremove pathprepend pathappend

#. aliases
alias cp='cp -i'
alias df='df -PH'
alias h='history'
alias man='LANG=C man'
alias mv='mv -i'
alias rehash='hash -r'   # see bash/checkhash
alias rm='rm -i'

type exa 2>/dev/null 1>&2
if [ $? -eq 0 ]; then
    alias ls='exa'
    alias ll='exa --long --header --git -a'
else
    alias ls='ls -G'
    alias ll='ls -lsa'
fi

case $(uname) in
    Darwin)
        alias ldd='otool -L'
        alias sss='open /System/Library/CoreServices/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine'
        ;;
esac

alias piconsole='screen /dev/cu.usbserial 115200'
alias radiogaga='ncmpcpp -h radiogaga.local'
