# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  TERM: xterm-256color

window:
  padding:
    x: 6
    y: 6

# Font configuration
font:
  size: 10

# Background opacity
background_opacity: 0.8
