- name: nginx configuration
  block:
    - name: create directories for nginx
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "~/Library/nginx"
        - "~/Library/Caches/nginx"
        - "~/Library/Logs/nginx"
    - name: create ~/Library/nginx/nginx.conf
      template:
        src: "nginx.conf.j2"
        dest: "~/Library/nginx/nginx.conf"
      notify: load nginx launchd service
    - name: launchd configuration for nginx
      template:
        src: "nyx.webserver.plist.j2"
        dest: "~/Library/LaunchAgents/nyx.webserver.plist"
      notify: load nginx launchd service
