# ~/.zshrc
set -o emacs

export LANG=fr_FR.UTF-8
export LC_MESSAGES=en_US.UTF-8

export PROMPT="%F{220}%n@%m %1~ %#%f "

export EDITOR=vim
export GIT_EDITOR=vim
export PAGER=less

# PATH
typeset -U path
path=("$HOME/.bin" '/usr/local/bin' $path)
[ -d "$HOME/go/bin" ] && path=("$HOME/go/bin" $path)
export PATH

# pyenv
export PYENV_ROOT=$HOME/.pyenv
path=("$PYENV_ROOT/bin" $PATH)
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# basic aliases
alias cp='cp -i'
alias df='df -PH'
alias h='history'
alias ll='ls -lsa'
alias ls='ls --color=auto'
alias mv='mv -i'
alias open='xdg-open'
alias rm='rm -i'
alias vi=vim

# setup lazy loading for executables functions files
fpath=($HOME/.config/zsh/functions $fpath)
for f in $HOME/.config/zsh/functions/*
do
    [ -x $f ] && autoload -Uz $f
done

# zsh-autosuggestions plugin
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
