---
- hosts: meushi
  become: no

  tasks:
    - {import_role: name=archlinux_user tasks_from=base, tags: ['base']}
    - {import_role: name=archlinux_user tasks_from=vscode, tags: ['vscode']}
    - {import_role: name=archlinux_user tasks_from=syncthing, tags: ['syncthing']}
