---
- hosts: meushi
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - import_role: name=archlinux tasks_from=kernel
    - import_role: name=archlinux tasks_from=base
    - import_role: name=archlinux tasks_from=network
    - import_role: name=archlinux tasks_from=audio
    - import_role: name=archlinux tasks_from=video
    - import_role: name=archlinux tasks_from=printer
    - import_role: name=archlinux tasks_from=fonts
    - import_role: name=archlinux tasks_from=gnome
    - import_role: name=archlinux tasks_from=userapps
