#
# ~/.bashrc for macOS
#

#. set locale
export LANG=fr_FR.UTF-8
export LC_MESSAGES=en_US.UTF-8

#. see man path-helper
eval $(/usr/libexec/path_helper -s)

#. PATH
export PATH=/opt/local/bin:/opt/local/sbin:$PATH    #  MacPorts
export PATH=$HOME/.cargo/bin:/usr/local/go/bin:$PATH
export PATH="$(python -m site --user-base)/bin":$PATH
export PATH=$HOME/.bin:$HOME/go/bin:$PATH

#. MacPorts

#. Interactive shell
if [ ! -z "$PS1" ]; then
    #. Bash setup
    #. for shopt buitlin see https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
    shopt -s cdspell checkhash checkwinsize
    shopt -s histappend histreedit histverify lithist
    if [[ $BASH_VERSION =~ ^4.* ]]; then
        shopt -s autocd direxpand dirspell
    fi
    export HISTCONTROL=ignoreboth:erasedups
    set -o emacs

    #. set bash prompt
    prompt_command () {
        local green='\e[0;36m'
        local red='\e[0;31m'
        local nc='\e[0m'

        if [[ -n $VIRTUAL_ENV ]]; then
            local venv="($(basename $VIRTUAL_ENV))"
        fi

        if [ $? -eq 0 ]; then local rc="ok"; else local rc="ko"; fi
        case $rc in
            ok) export PS1="${green}\u@\h $venv~> ${nc}";;
            ko) export PS1="${red}\u@\h $venv~> ${nc}";;
        esac
    }
    export PROMPT_COMMAND=prompt_command

    #. add ":" to re-enable access to the standard system man pages
    export MANPATH=$MANPATH:

    #. add environment variables for interactive shell
    export EDITOR=vi
    export GIT_EDITOR=vi
    export PAGER=less

    source /opt/local/etc/profile.d/bash_completion.sh
    [ -f ./.aliases ] && source ./.aliases
fi
