- name: load dropbackup launchd service
  command: "{{ item }}"
  loop:
    - launchctl unload ~/Library/LaunchAgents/nyx.dropbackup.plist
    - launchctl load   ~/Library/LaunchAgents/nyx.dropbackup.plist
